name: dev
channels:
  - defaults
dependencies:
  - python==3.10
  - pip
  - pip:
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - loguru
    - matplotlib
    - libsvmdata
    - pyyaml
    - tqdm
    - jupyterlab
    - torch
    - torchvision
    - torchaudio
    - timm==0.8.3.dev0  # fix this after a stable release of 0.8 is out
    - git+https://github.com/openai/CLIP.git
    - tensorflow
    - tensorflow-datasets
